### ISSUE TITLE
mate-system-monitor - System Information does not show the Debian point release version number (10.5)

### ISSUE THREAD

**Issue by kimariterikishi** [mate-desktop/debian-packages#105]
It shows a single output, maybe this is what the graphics application should be set to **point release version number**:

```
cat /etc/debian_version
10.5
```

The command do not show the point release version number:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
cat /etc/issue
Debian GNU/Linux 10 \n \l
```

```
hostnamectl
   Static hostname: ...
         Icon name: computer-laptop
           Chassis: laptop
           ...
  Operating System: Debian GNU/Linux 10 (buster)
      Architecture: x86-64
```

```
inxi -S
System:
  ...
  Distro: Debian GNU/Linux 10 (buster) 
```

Represented in pictures:
(**mate-system-monitor is not show the point release version number**: five in 10.5):
![Debian 10 Buster, MATE (mate-system-monitor) - System Information_01](https://user-images.githubusercontent.com/44789359/89121061-f0137000-d4bb-11ea-86b8-83e70754d3f2.png)
![Debian 10 Buster, MATE (mate-system-monitor) - System Information_02](https://user-images.githubusercontent.com/44789359/89121064-f1449d00-d4bb-11ea-8cdc-0b306d68b88b.png)

It's not a dangerous problem, but if the user is already updating, see what the reality is.

**Comment by sc0w** [comment]
the work is done with https://github.com/mate-desktop/mate-system-monitor/commit/e59ca718f11094b8ba2123febe017a5b43244bb0 since 1.24
