### ISSUE TITLE
download.py

### ISSUE THREAD

**Issue by cpatrick08** [mate-desktop/debian-packages#74]
Could you make it so download.py downloads the 1.10 packages and could you update the mate-user-guide to 1.10

**Comment by monsta** [comment]
It simply downloads the latest version specified at the top of ```debian/changelog``` file of each package.
@stefano-k: time to update :)

**Comment by cpatrick08** [comment]
some of the packages are updated, but not all of them

**Comment by monsta** [comment]
I think all packages are at 1.10.x now
