### ISSUE TITLE
pluma won't build

### ISSUE THREAD

**Issue by cpatrick08** [mate-desktop/debian-packages#75]
linked is the pluma.log that the build produced with the entire build in it. http://pastebin.com/CeRPZeDh

**Comment by monsta** [comment]
Which version of Debian/Ubuntu?

**Comment by cpatrick08** [comment]
Ubuntu Mate 15.10 64bit

**Comment by monsta** [comment]
Ok, I'll check it. Currently I can't reproduce it in Debian Testing; did you try building it there (or in other Debian version)?

**Comment by cpatrick08** [comment]
No,  just Ubuntu

**Comment by monsta** [comment]
Can't reproduce it in Ubuntu 15.10. I used the stock pluma package, obtained via apt-get source.

```
monsta@mate:~/4/pluma-1.8.1+dfsg1$ dpkg-buildpackage -b -us -uc -rfakeroot

...

make[3]: выход из каталога «/home/monsta/4/pluma-1.8.1+dfsg1/po»
Making all in data
make[3]: вход в каталог «/home/monsta/4/pluma-1.8.1+dfsg1/data»
LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po pluma.desktop.in pluma.desktop
Generating and caching the translation database
Merging translations into pluma.desktop.
/bin/sed \
	-e 's^\@GETTEXT_PACKAGE\@^pluma^g' \
	-e 's^\@ACTIVE_PLUGINS\@^'docinfo', 'modelines', 'filebrowser', 'spell', 'time'^g' \
	-e 's^\@TOOLBAR_STYLE\@^PLUMA_TOOLBAR_SYSTEM^g' \
	< org.mate.pluma.gschema.xml.in.in > org.mate.pluma.gschema.xml.in
LC_ALL=C /usr/bin/intltool-merge  -x -u --no-translations org.mate.pluma.gschema.xml.in org.mate.pluma.gschema.xml
Merging translations into org.mate.pluma.gschema.xml.
CREATED org.mate.pluma.gschema.xml
/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas --strict --dry-run  --schema-file=org.mate.pluma.gschema.xml && mkdir -p . && touch org.mate.pluma.gschema.valid
rm org.mate.pluma.gschema.xml.in
make[3]: выход из каталога «/home/monsta/4/pluma-1.8.1+dfsg1/data»

...

```

How did you build the package?
Did you combine ```debian/``` dir from the stock 1.8.x package with 1.10 tarball, or used some other method?

**Comment by monsta** [comment]
Tested it in 15.10, got the same messages and successful build.

**Comment by cpatrick08** [comment]
I downloaded the git package for pluma ran git log on the directory and added the 1.10 info to the top of the changelog to get the debian-pckages to build from the 1.10 tarball

**Comment by monsta** [comment]
Try getting the package from http://pub.mate-desktop.org/releases/1.10/ instead of github tarball.
Also you don't need the latest version mentioned in ```debian/changelog```, it will build fine even with 1.9.x written there.

**Comment by cpatrick08** [comment]
I'm sure it would build if iI removed 1.10 firmthe changelog, but iIlike to build it from latest version/ development Verizon whichever is newer

**Comment by monsta** [comment]
Well I can't reproduce the issue anyway, so it's up to you to experiment :)

**Comment by cpatrick08** [comment]
changed changelog back to default and still get same error message

**Comment by cpatrick08** [comment]
deleted folder and started from scratch will report with any other error problems
