### ISSUE TITLE
Atril won't build

### ISSUE THREAD

**Issue by cpatrick08** [mate-desktop/debian-packages#80]
Linked it the Atril.log file that the build produced with the entire build in it. Running Ubuntu Mate 15.10 64 bit http://1drv.ms/1QTYZ40

**Comment by monsta** [comment]
Unreproducible, ```./debian-packages/build.py atril``` completes successfully here in 15.10.
Since your issue comes from the only C++ lib in the project, again, check your g++ setup. Something is probably wrong with it, https://github.com/mate-desktop/debian-packages/issues/79 tells me the same.
