### ISSUE TITLE
drop blueman?

### ISSUE THREAD

**Issue by monsta** [mate-desktop/debian-packages#85]
Blueman tarballs aren't stored in http://pub.mate-desktop.org/releases/ (so download script doesn't work for it), and it doesn't follow MATE versions, so there's no use storing its ```debian/``` folder here.
I propose removing it.

@clefebvre @flexiondotorg 
thoughts guys?

**Comment by flexiondotorg** [comment]
Agree. This is maintained in the distros now. Debian, Ubuntu, Arch Linux for example.

**Comment by monsta** [comment]
Yes - and Christopher even does it himself in Debian (and maybe Ubuntu as well) :smile:

**Comment by clefebvre** [comment]
ok
