### ISSUE TITLE
mate-polkit fails building

### ISSUE THREAD

**Issue by EclipseSpark** [mate-desktop/debian-packages#94]
mate-polkit fails by saying that the debian/mate-polkit.install was unable to find any installable files under /usr/lib/*/mate-polkit

infact in debian/tmp/usr/lib/*/ there is no mate-polkit folder

tested on debian testing after having compiled and installed the following mate components
atril
caja
caja-dropbox
caja-extensions
engrampa
eom
libmatekbd
libmatemixer
libmateweather
marco
mate-applets
mate-backgrounds
mate-common
mate-control-center
mate-desktop
mate-desktop-environment
mate-icon-theme
mate-icon-theme-faenza
mate-indicator-applet
mate-media
mate-menus
mate-netbook
mate-notification-daemon
mate-panel
mate-settings-daemon
mate-system-monitor
mate-themes
mate-user-share

**Comment by EclipseSpark** [comment]
i am testing a build with this patch https://github.com/mate-desktop/debian-packages/pull/95 (just changed the inclusion path according to where the build scripts place the new file)

**Comment by monsta** [comment]
@flexiondotorg: indeed, https://github.com/mate-desktop/debian-packages/commit/a436320ccb05731d794e529a5f5b4f004db5abbc breaks the build - and I don't see that new path in pkg-mate repos at all :confused:

**Comment by monsta** [comment]
@EclipseSpark: thanks, https://github.com/mate-desktop/debian-packages/pull/95 is merged.

**Comment by EclipseSpark** [comment]
ok, i'll retry and give you better info, i have used the debian folder inside the source code taken from the mate snapshota repo, not from github
