### ISSUE TITLE
Screenshot Highlighting Box Refresh Issue

### ISSUE THREAD

**Issue by frictionlessmeme** [mate-desktop/debian-packages#96]
I'm not even sure this is the appropriate place to post this bug, because I am unsure what component of the OS it belongs to, but I am making a guess that the problem lies with MATE.

I run Debian GNU/Linux 8, and installed MATE Desktop Environment 1.8.1 (from the repos, I think).

I persistently have a problem with the screenshot app. The "whole desktop" and "current window" options work perfectly, but the "select area to grab" option does not always work properly.

When you click and drag to draw a box around the area you want to grab, the box is filled in in pink. Frequently, when you release the mouse button to take the photo, the pink box does not disappear before the screenshot is taken, meaning that some of the resulting screenshot contains pink areas. It is often necessary to take the screenshot several times to manage to get one that does not contain any pink.

The first attached pic is a perfect screenshot, and the others show what happens when it goes wrong.

![screenshot-6](https://cloud.githubusercontent.com/assets/6946603/19900182/81424172-a05a-11e6-8ded-da91cac86af7.png)
![screenshot-9](https://cloud.githubusercontent.com/assets/6946603/19900179/812fd578-a05a-11e6-9505-3df1fd007659.png)
![screenshot-8](https://cloud.githubusercontent.com/assets/6946603/19900180/8133c99e-a05a-11e6-921f-e87f9f325193.png)
![screenshot-7](https://cloud.githubusercontent.com/assets/6946603/19900181/81387a2a-a05a-11e6-9d84-869b7469019a.png)

**Comment by EclipseSpark** [comment]
i have already experieced the same bug wuth mate 1.8.1, but i haven't seen it anymore with the recent versions of MATE

if i am not wrong, the involved debian package should be mate-utils, and infact as you can see, there are many not so recent commits involving how mate-screenshots work
https://github.com/mate-desktop/mate-utils/commits/master

it was probably fixed here https://github.com/mate-desktop/mate-utils/commit/206323736d82a707230e02eab1f891fdfd652e7f

**Comment by monsta** [comment]
This doesn't belong to Debian packaging repo. If anyone still sees it with 1.16 or 1.18, it should be reported in mate-utils.
