### ISSUE TITLE
Mate in OpenBSD Ports

### ISSUE THREAD

**Issue by kloun** [mate-desktop/debian-packages#97]
MAKE SUBJ, PLEASE.

**Comment by crayxt** [comment]
https://github.com/jasperla/openbsd-wip/tree/master/x11/mate

**Comment by ynoauun** [comment]
So what's the status of MATE on OpenBSD?

**Comment by ynoauun** [comment]
ping, @crayxt @kloun

**Comment by monsta** [comment]
Not sure how it got into Debian packaging repo, but it doesn't belong here.

**Comment by ynoauun** [comment]
https://github.com/jasperla/openbsd-wip/issues/69
